[env:nucleo_f401re]
platform  = ststm32
board     = nucleo_f401re
framework = arduino

lib_deps =
    adafruit/Adafruit BME280 Library @ ^2.2.4
    adafruit/Adafruit SSD1306 @ ^2.5.9
    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/DHT sensor library @ ^1.4.6
    knolleary/PubSubClient @ ^2.8.0
    stm32duino/STM32FreeRTOS @ ^10.4.6
    sandeepmistry/LoRa @ ^0.8.0
    bblanchon/ArduinoJson @ ^7.1.0

build_flags =
    -DUSE_FREERTOS=1
    -IInclude
    -DSTM32F4xx

monitor_speed = 115200

; ─── LoRa activé ─────────────────────────────────────────
; [env:nucleo_f401re_lora]
; extends = env:nucleo_f401re
; build_flags = ${env:nucleo_f401re.build_flags} -DUSE_LORA=1

; ─── Caméra activée ──────────────────────────────────────
; [env:nucleo_f401re_cam]
; extends = env:nucleo_f401re
; build_flags = ${env:nucleo_f401re.build_flags} -DUSE_CAMERA=1

; ─── Tout activé (production) ────────────────────────────
; [env:nucleo_f401re_full]
; extends = env:nucleo_f401re
; build_flags = ${env:nucleo_f401re.build_flags} -DUSE_LORA=1 -DUSE_CAMERA=1
