apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: meteo-org
      defaultBucket: station
      tlsSkipVerify: true
    secureJsonData:
      token: meteo-super-token-changeme
    isDefault: true
